
const recipes = [
  {
    title: "Spaghetti Carbonara",
    category: "Pasta",
    image: "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
    ingredients: [
      "200g spaghetti",
      "100g pancetta",
      "2 large eggs",
      "50g Pecorino Romano cheese",
      "Black pepper",
      "Salt",
    ],
    instructions: [
      "Cook the spaghetti in salted boiling water until al dente.",
      "While the pasta is cooking, cut the pancetta into small cubes and fry until crispy.",
      "In a bowl, whisk together the eggs, cheese, and a generous amount of black pepper.",
      "Drain the spaghetti and add it to the pancetta pan. Mix well.",
      "Remove the pan from the heat and add the egg mixture, stirring quickly to create a creamy sauce.",
      "Serve immediately with extra cheese and pepper.",
    ],
  },
  {
    title: "Classic Margherita Pizza",
    category: "Pizza",
    image: "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
    ingredients: [
      "250g strong bread flour",
      "1 tsp dried yeast",
      "1 tsp sugar",
      "1 tsp salt",
      "150ml warm water",
      "2 tbsp olive oil",
      "100g tomato sauce",
      "150g mozzarella cheese",
      "Fresh basil leaves",
    ],
    instructions: [
      "In a large bowl, combine flour, yeast, sugar, and salt.",
      "Add warm water and olive oil, and mix to form a dough.",
      "Knead the dough for about 10 minutes until smooth.",
      "Let the dough rise in a warm place for 1 hour.",
      "Preheat oven to 220°C (425°F).",
      "Roll out the dough on a floured surface.",
      "Spread tomato sauce over the base, add mozzarella cheese, and bake for 15-20 minutes.",
      "Garnish with fresh basil leaves before serving.",
    ],
  },
  // More Pizza recipes
  {
    title: "Pepperoni Pizza",
    category: "Pizza",
    image: "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
    ingredients: [
      "250g pizza dough",
      "100g tomato sauce",
      "150g mozzarella cheese",
      "80g pepperoni slices",
      "1 tbsp olive oil",
      "1/2 tsp dried oregano",
    ],
    instructions: [
      "Preheat oven to 220°C (425°F).",
      "Roll out the pizza dough on a floured surface.",
      "Spread tomato sauce evenly over the base.",
      "Sprinkle mozzarella cheese on top.",
      "Arrange pepperoni slices over the cheese.",
      "Drizzle with olive oil and sprinkle oregano.",
      "Bake for 12-15 minutes until golden and bubbly.",
    ],
  },
  {
    title: "Vegetarian Supreme Pizza",
    category: "Pizza",
    image: "https://www.themealdb.com/images/media/meals/xxpqsy1511452222.jpg",
    ingredients: [
      "250g pizza dough",
      "100g tomato sauce",
      "120g mozzarella cheese",
      "1/2 red bell pepper, sliced",
      "1/2 green bell pepper, sliced",
      "1/2 red onion, sliced",
      "50g black olives, sliced",
      "50g mushrooms, sliced",
      "1 tsp dried Italian herbs",
    ],
    instructions: [
      "Preheat oven to 220°C (425°F).",
      "Roll out the pizza dough and place on a baking tray.",
      "Spread tomato sauce over the base.",
      "Add mozzarella cheese, bell peppers, onion, olives, and mushrooms.",
      "Sprinkle with Italian herbs.",
      "Bake for 15-18 minutes until crust is golden.",
    ],
  },
  {
    title: "BBQ Chicken Pizza",
    category: "Pizza",
    image: "https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg",
    ingredients: [
      "250g pizza dough",
      "100g barbecue sauce",
      "150g cooked chicken breast, shredded",
      "100g mozzarella cheese",
      "1/2 red onion, thinly sliced",
      "1 tbsp chopped fresh cilantro",
    ],
    instructions: [
      "Preheat oven to 220°C (425°F).",
      "Roll out pizza dough and place on a baking sheet.",
      "Spread barbecue sauce over the base.",
      "Top with mozzarella cheese, shredded chicken, and red onion.",
      "Bake for 12-15 minutes until cheese is melted and crust is golden.",
      "Garnish with chopped cilantro before serving.",
    ],
  },
  {
    title: "Chocolate Brownies",
    category: "Dessert",
    image: "https://www.themealdb.com/images/media/meals/yypvst1511386427.jpg",
    ingredients: [
      "150g unsalted butter",
      "200g dark chocolate",
      "150g sugar",
      "2 large eggs",
      "100g all-purpose flour",
      "30g cocoa powder",
      "1 tsp vanilla extract",
      "Pinch of salt",
    ],
    instructions: [
      "Preheat oven to 180°C (350°F). Grease and line a square baking tin.",
      "Melt butter and chocolate together over low heat.",
      "In a bowl, whisk together sugar and eggs until light and fluffy.",
      "Stir in the melted chocolate mixture and vanilla extract.",
      "In a separate bowl, whisk together flour, cocoa powder, and salt.",
      "Gently fold the dry ingredients into the wet ingredients until just combined.",
      "Pour the batter into the prepared tin and bake for 20-25 minutes.",
      "Let it cool completely before cutting into squares.",
    ],
  },
  // Dessert recipes
  {
    title: "Lemon Cheesecake",
    category: "Dessert",
    image: "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
    ingredients: [
      "200g digestive biscuits",
      "100g unsalted butter, melted",
      "400g cream cheese",
      "150g sugar",
      "2 large eggs",
      "1 lemon, zested and juiced",
      "1 tsp vanilla extract",
    ],
    instructions: [
      "Crush the biscuits and mix with melted butter. Press into the base of a springform tin.",
      "Beat cream cheese and sugar until smooth. Add eggs one at a time, mixing well.",
      "Stir in lemon zest, juice, and vanilla extract.",
      "Pour mixture over the biscuit base.",
      "Bake at 160°C (320°F) for 40-45 minutes. Let cool, then chill before serving.",
    ],
  },
  {
    title: "Strawberry Shortcake",
    category: "Dessert",
    image: "https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg",
    ingredients: [
      "2 cups all-purpose flour",
      "1/4 cup sugar",
      "1 tbsp baking powder",
      "1/2 tsp salt",
      "1/2 cup cold butter",
      "2/3 cup milk",
      "1 egg",
      "2 cups fresh strawberries, sliced",
      "1/4 cup sugar (for strawberries)",
      "1 cup whipped cream",
    ],
    instructions: [
      "Preheat oven to 220°C (425°F).",
      "Mix strawberries with 1/4 cup sugar and set aside.",
      "In a bowl, combine flour, sugar, baking powder, and salt.",
      "Cut in butter until mixture resembles coarse crumbs.",
      "Whisk milk and egg together, then add to dry ingredients. Mix until just combined.",
      "Drop spoonfuls onto a baking sheet and bake for 12-15 minutes.",
      "Split shortcakes, fill with strawberries and whipped cream, and serve.",
    ],
  },
  {
    title: "Classic Tiramisu",
    category: "Dessert",
    image: "https://www.themealdb.com/images/media/meals/xxtsvx1511814083.jpg",
    ingredients: [
      "250g mascarpone cheese",
      "3 large eggs, separated",
      "100g sugar",
      "200ml strong coffee, cooled",
      "2 tbsp coffee liqueur (optional)",
      "200g ladyfinger biscuits",
      "2 tbsp cocoa powder",
    ],
    instructions: [
      "Beat egg yolks with half the sugar until pale and thick.",
      "Add mascarpone and mix until smooth.",
      "In a separate bowl, whisk egg whites with remaining sugar until stiff peaks form. Fold into mascarpone mixture.",
      "Combine coffee and liqueur in a shallow dish. Dip ladyfingers briefly and layer in a dish.",
      "Spread half the mascarpone mixture over the ladyfingers. Repeat layers.",
      "Dust with cocoa powder and chill for at least 4 hours before serving.",
    ],
  },
  {
    title: "Fresh Garden Salad",
    category: "Salad",
    image: "https://www.themealdb.com/images/media/meals/urtwux1486983078.jpg",
    ingredients: [
      "6 cups mixed salad greens",
      "2 medium tomatoes, diced",
      "1 cucumber, sliced",
      "1 red onion, thinly sliced",
      "1 bell pepper, chopped",
      "1/2 cup olive oil",
      "3 tbsp balsamic vinegar",
      "1 tsp Dijon mustard",
      "1 clove garlic, minced",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Wash and dry all vegetables thoroughly.",
      "In a large bowl, combine the salad greens, tomatoes, cucumber, red onion, and bell pepper.",
      "In a small bowl, whisk together olive oil, balsamic vinegar, Dijon mustard, minced garlic, salt, and pepper.",
      "Drizzle the dressing over the salad and toss gently to combine.",
      "Serve immediately.",
    ],
  },
  // More Salad recipes
  {
    title: "Greek Salad",
    category: "Salad",
    image: "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
    ingredients: [
      "3 cups chopped romaine lettuce",
      "1 cup cherry tomatoes, halved",
      "1 cucumber, sliced",
      "1/2 red onion, thinly sliced",
      "1/2 cup Kalamata olives",
      "1/2 cup feta cheese, crumbled",
      "2 tbsp olive oil",
      "1 tbsp red wine vinegar",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine lettuce, tomatoes, cucumber, red onion, and olives.",
      "In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper.",
      "Pour the dressing over the salad and toss gently.",
      "Top with crumbled feta cheese and serve.",
    ],
  },
  {
    title: "Quinoa Avocado Salad",
    category: "Salad",
    image: "https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg",
    ingredients: [
      "1 cup cooked quinoa",
      "1 avocado, diced",
      "1 cup cherry tomatoes, halved",
      "1/4 cup red onion, finely chopped",
      "1/4 cup fresh cilantro, chopped",
      "2 tbsp olive oil",
      "1 tbsp lime juice",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine cooked quinoa, avocado, cherry tomatoes, red onion, and cilantro.",
      "In a small bowl, whisk together olive oil, lime juice, salt, and pepper.",
      "Drizzle the dressing over the salad and toss gently.",
      "Serve chilled or at room temperature.",
    ],
  },
  {
    title: "Asian Cabbage Slaw",
    category: "Salad",
    image: "https://www.themealdb.com/images/media/meals/1549542994.jpg",
    ingredients: [
      "3 cups shredded green cabbage",
      "1 cup shredded red cabbage",
      "1 carrot, julienned",
      "2 green onions, sliced",
      "1/4 cup chopped peanuts",
      "2 tbsp soy sauce",
      "1 tbsp rice vinegar",
      "1 tbsp sesame oil",
      "1 tsp honey",
      "1 tsp grated ginger",
    ],
    instructions: [
      "In a large bowl, combine green cabbage, red cabbage, carrot, and green onions.",
      "In a small bowl, whisk together soy sauce, rice vinegar, sesame oil, honey, and grated ginger.",
      "Pour the dressing over the vegetables and toss to coat.",
      "Top with chopped peanuts before serving.",
    ],
  },
  {
    title: "Grilled Salmon with Lemon Herbs",
    category: "Main Course",
    image: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    ingredients: [
      "4 salmon fillets",
      "2 tbsp olive oil",
      "2 cloves garlic, minced",
      "1 lemon, sliced",
      "2 tbsp fresh dill, chopped",
      "2 tbsp fresh parsley, chopped",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat grill to medium-high heat.",
      "In a small bowl, mix olive oil, minced garlic, dill, and parsley.",
      "Place salmon fillets on a large piece of aluminum foil. Season with salt and pepper.",
      "Spread the herb mixture over the salmon fillets and top with lemon slices.",
      "Fold the foil to create a sealed packet. Grill for 12-15 minutes, or until salmon is cooked through.",
      "Serve hot with your favorite sides.",
    ],
  },

  {
    title: "Vegetable Stir-Fry",
    category: "Stir-Fry",
    image: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
    ingredients: [
      "2 cups mixed vegetables (bell peppers, broccoli, carrots)",
      "1 cup tofu, cubed",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "2 cloves garlic, minced",
      "1 tsp ginger, grated",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Heat sesame oil in a large pan over medium heat.",
      "Add garlic and ginger, sauté for 1 minute.",
      "Add tofu and cook until golden brown.",
      "Add mixed vegetables and stir-fry for 5-7 minutes.",
      "Pour in soy sauce and season with salt and pepper.",
      "Serve hot over rice or noodles.",
    ],
  },
  {
    title: "Chicken Tacos",
    category: "Mexican",
    image: "https://www.themealdb.com/images/media/meals/1525876460.jpg",
    ingredients: [
      "2 chicken breasts, cooked and shredded",
      "8 small corn tortillas",
      "1 cup lettuce, shredded",
      "1 cup tomatoes, diced",
      "1 avocado, sliced",
      "1/2 cup salsa",
      "1/2 cup sour cream",
      "Lime wedges for serving",
    ],
    instructions: [
      "Warm the tortillas in a dry skillet over medium heat.",
      "In each tortilla, add shredded chicken, lettuce, tomatoes, avocado, salsa, and sour cream.",
      "Serve with lime wedges on the side.",
    ],
  },
  {
    title: "Beef Stroganoff",
    category: "Main Course",
    image: "https://www.themealdb.com/images/media/meals/x0l8nq1511386427.jpg",
    ingredients: [
      "500g beef sirloin, sliced",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "200g mushrooms, sliced",
      "1 cup beef broth",
      "1 cup sour cream",
      "2 tbsp flour",
      "Salt and pepper to taste",
      "Egg noodles for serving",
    ],
    instructions: [
      "In a large skillet, brown the beef slices over medium heat.",
      "Add onions and garlic, sauté until softened.",
      "Stir in mushrooms and cook until tender.",
      "Sprinkle flour over the mixture and stir well.",
      "Pour in beef broth and bring to a simmer.",
      "Reduce heat and stir in sour cream. Season with salt and pepper.",
      "Serve over cooked egg noodles.",
    ],
  },
];

export default recipes;
